Repository henkelmax/simple-voice-chat, pull requests merged in 2024-03, with the labels that each got.

#672 Update translation of zh_cn.json
  common/src/main/resources/assets/voicechat/lang/zh_cn.json
Labels: translation

#674 Implement Velocity Proxy
  common-proxy/build.gradle
  common-proxy/gradle.properties
  common-proxy/src/main/java/de/maxhenkel/voicechat/VoiceProxy.java
  common-proxy/src/main/java/de/maxhenkel/voicechat/config/ProxyConfig.java
  common-proxy/src/main/java/de/maxhenkel/voicechat/debug/PingHandler.java
  common-proxy/src/main/java/de/maxhenkel/voicechat/logging/LogLevel.java
  common-proxy/src/main/java/de/maxhenkel/voicechat/logging/VoiceChatLogger.java
  common-proxy/src/main/java/de/maxhenkel/voicechat/network/VoiceProxyBridgeManager.java
  common-proxy/src/main/java/de/maxhenkel/voicechat/network/VoiceProxyServer.java
  common-proxy/src/main/java/de/maxhenkel/voicechat/sniffer/SniffedSecretPacket.java
  common-proxy/src/main/java/de/maxhenkel/voicechat/sniffer/VoiceProxySniffer.java
  common-proxy/src/main/java/de/maxhenkel/voicechat/util/ByteBufferWrapper.java
  common-proxy/src/main/java/de/maxhenkel/voicechat/util/VarIntUtils.java
  common-proxy/src/template/java/de/maxhenkel/voicechat/BuildConstants.java
  settings.gradle
  velocity/build.gradle
  velocity/changelog.md
  velocity/gradle.properties
  velocity/src/main/java/de/maxhenkel/voicechat/SimpleVoiceChatVelocity.java
  velocity/src/main/java/de/maxhenkel/voicechat/logging/JavaLoggingLogger.java
Labels: enhancement

#676 Implement Waterfall/Bungeecord
  bungeecord/build.gradle
  bungeecord/changelog.md
  bungeecord/gradle.properties
  bungeecord/src/main/java/de/maxhenkel/voicechat/BungeecordPlugin.java
  bungeecord/src/main/java/de/maxhenkel/voicechat/SimpleVoiceChatBungeecord.java
  bungeecord/src/main/java/de/maxhenkel/voicechat/logging/JavaLoggingLogger.java
  bungeecord/src/main/resources/bungee.yml
  gradle.properties
  settings.gradle
Labels: enhancement

#683 [Proxy] Add support for unresolved InetSocketAddress
  common-proxy/src/main/java/de/maxhenkel/voicechat/VoiceProxy.java
  velocity/src/main/java/de/maxhenkel/voicechat/SimpleVoiceChatVelocity.java
Labels: bug
